version: "3"

networks:
  etcd:
    driver: bridge

services:
  etcd:
    user: "0"
    image: "quay.io/coreos/etcd:v3.5.16"
    container_name: "etcd"
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Shanghai
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/data/etcd:/var/lib/etcd"
      - "/data/etcd/data:/data/etcd/data"
      - "/data/etcd/config/etcd.conf.yml:/etc/etcd/etcd.conf.yml"
      - "/etc/localtime:/etc/localtime:ro"
    command: /usr/local/bin/etcd \
      --config-file=/etc/etcd/etcd.conf.yml
